Fix unhandled exception when generating bootstrap script.
bug introduced in 80f3229cd8c2bce0816b2116e39eb080c336d142

ERROR: unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/bin/rhn-bootstrap", line 46, in <module>
    sys.exit(mod.main() or 0)
  File "/usr/share/rhn/certs/rhn_bootstrap.py", line 637, in main
    generateBootstrapScript(options)
  File "/usr/share/rhn/certs/rhn_bootstrap.py", line 577, in generateBootstrapScript
    1 - options.no_up2date, pubname)
  File "/usr/share/rhn/certs/rhn_bootstrap_strings.py", line 178, in getHeader
    org_gpg_key = ",".join([os.path.basename(gpg_key) for gpg_key in options.gpg_key.split(",")])
NameError: global name 'options' is not defined

(cherry picked from commit 5df22a1acf3f945d9d848e9ab9df5cd70e84b09e)

Orabug: 28984819

Signed-off-by: Laurence Rochfort <laurence.rochfort@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>
Reviewed-by: Anton Krylov <anton.krylov@oracle.com>